import { supabase } from './client';
import { getCurrentBroker } from './brokers';
import type { Application, ApplicationInsert, ApplicationUpdate, ApplicationWithBorrowers, ApplicationStats } from '../types/database';

/**
 * Generate a unique upload token for borrower portal
 */
function generateUploadToken(): string {
  return Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
}

/**
 * Get all applications for the current broker
 */
export async function getApplications(): Promise<Application[]> {
  const broker = await getCurrentBroker();
  
  if (!broker) {
    throw new Error('Not authenticated');
  }
  
  const { data, error } = await supabase
    .from('applications')
    .select('*')
    .eq('broker_id', broker.id)
    .is('deleted_at', null)
    .order('created_at', { ascending: false });
  
  if (error) {
    console.error('Error fetching applications:', error);
    throw error;
  }
  
  return data || [];
}

/**
 * Get all applications with borrower information
 */
export async function getApplicationsWithBorrowers(): Promise<ApplicationWithBorrowers[]> {
  const broker = await getCurrentBroker();
  
  if (!broker) {
    throw new Error('Not authenticated');
  }
  
  const { data, error } = await supabase
    .from('applications')
    .select(`
      *,
      borrowers (*)
    `)
    .eq('broker_id', broker.id)
    .is('deleted_at', null)
    .order('created_at', { ascending: false });
  
  if (error) {
    console.error('Error fetching applications with borrowers:', error);
    throw error;
  }
  
  return data || [];
}

/**
 * Get a single application by ID
 */
export async function getApplicationById(id: string): Promise<Application | null> {
  const broker = await getCurrentBroker();
  
  if (!broker) {
    throw new Error('Not authenticated');
  }
  
  const { data, error } = await supabase
    .from('applications')
    .select('*')
    .eq('id', id)
    .eq('broker_id', broker.id)
    .is('deleted_at', null)
    .single();
  
  if (error) {
    if (error.code === 'PGRST116') {
      // No rows returned
      return null;
    }
    console.error('Error fetching application:', error);
    throw error;
  }
  
  return data;
}

/**
 * Get a single application with borrowers by ID
 */
export async function getApplicationWithBorrowersById(id: string): Promise<ApplicationWithBorrowers | null> {
  const broker = await getCurrentBroker();
  
  if (!broker) {
    throw new Error('Not authenticated');
  }
  
  const { data, error } = await supabase
    .from('applications')
    .select(`
      *,
      borrowers (*)
    `)
    .eq('id', id)
    .eq('broker_id', broker.id)
    .is('deleted_at', null)
    .single();
  
  if (error) {
    if (error.code === 'PGRST116') {
      return null;
    }
    console.error('Error fetching application with borrowers:', error);
    throw error;
  }
  
  return data;
}

/**
 * Create a new application
 */
export async function createApplication(application: Omit<ApplicationInsert, 'broker_id' | 'upload_token'>): Promise<Application> {
  const broker = await getCurrentBroker();
  
  if (!broker) {
    throw new Error('Not authenticated');
  }

// Don't send upload_token - let Supabase generate it with uuid_generate_v4()
  const { data, error } = await supabase
    .from('applications')
    .insert({
      ...application,
      broker_id: broker.id,
      // upload_token will be auto-generated by database
    })  
    .select()
    .single();
  
if (error) {
  console.error('Supabase error creating application:', {
    message: error.message,
    details: error.details,
    hint: error.hint,
    code: error.code,
  });
  throw error;
}
  
  return data;
}

/**
 * Update an existing application
 */
export async function updateApplication(id: string, updates: ApplicationUpdate): Promise<Application> {
  const broker = await getCurrentBroker();
  
  if (!broker) {
    throw new Error('Not authenticated');
  }
  
  const { data, error } = await supabase
    .from('applications')
    .update(updates)
    .eq('id', id)
    .eq('broker_id', broker.id)
    .is('deleted_at', null)
    .select()
    .single();
  
  if (error) {
    console.error('Error updating application:', error);
    throw error;
  }
  
  return data;
}

/**
 * Update application status
 */
export async function updateApplicationStatus(
  id: string,
  status: Application['status']
): Promise<Application> {
  return updateApplication(id, { status });
}

/**
 * Soft delete an application
 */
export async function deleteApplication(id: string): Promise<void> {
  const broker = await getCurrentBroker();
  
  if (!broker) {
    throw new Error('Not authenticated');
  }
  
  const { error } = await supabase
    .from('applications')
    .update({ deleted_at: new Date().toISOString() })
    .eq('id', id)
    .eq('broker_id', broker.id);
  
  if (error) {
    console.error('Error deleting application:', error);
    throw error;
  }
}

/**
 * Get application statistics for dashboard
 */
export async function getApplicationStats(): Promise<ApplicationStats> {
  const broker = await getCurrentBroker();
  
  if (!broker) {
    throw new Error('Not authenticated');
  }
  
  const { data, error } = await supabase
    .from('applications')
    .select('status')
    .eq('broker_id', broker.id)
    .is('deleted_at', null);
  
  if (error) {
    console.error('Error fetching application stats:', error);
    throw error;
  }
  
  const stats: ApplicationStats = {
    total: data.length,
    draft: 0,
    collecting: 0,
    organized: 0,
    analyzed: 0,
    submitted: 0,
    approved: 0,
    rejected: 0,
    complete: 0,
  };
  
  data.forEach(app => {
    stats[app.status]++;
  });
  
  return stats;
}

/**
 * Search and filter applications
 */
export async function searchApplications(
  searchTerm?: string,
  status?: Application['status'],
  dateFrom?: Date,
  dateTo?: Date
): Promise<Application[]> {
  const broker = await getCurrentBroker();
  
  if (!broker) {
    throw new Error('Not authenticated');
  }
  
  let query = supabase
    .from('applications')
    .select('*')
    .eq('broker_id', broker.id)
    .is('deleted_at', null);
  
  // Apply filters
  if (status) {
    query = query.eq('status', status);
  }
  
  if (dateFrom) {
    query = query.gte('created_at', dateFrom.toISOString());
  }
  
  if (dateTo) {
    query = query.lte('created_at', dateTo.toISOString());
  }
  
  // Apply search term (searches in property_address and city)
  if (searchTerm && searchTerm.trim()) {
    query = query.or(`property_address.ilike.%${searchTerm}%,city.ilike.%${searchTerm}%`);
  }
  
  query = query.order('created_at', { ascending: false });
  
  const { data, error } = await query;
  
  if (error) {
    console.error('Error searching applications:', error);
    throw error;
  }
  
  return data || [];
}

/**
 * Subscribe to real-time changes for applications
 */
export function subscribeToApplications(
  callback: (payload: any) => void
) {
  return supabase
    .channel('applications-changes')
    .on(
      'postgres_changes',
      {
        event: '*',
        schema: 'public',
        table: 'applications',
      },
      callback
    )
    .subscribe();
}
